apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy90cmF2ZWxtZW1vcnk=
#mongo_uri=mongodb://mongodb-service.database.svc.cluster.local:27017/travelmemory
