apiVersion: v1
kind: Service
metadata:
  name: tmfeservice
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app: tmfeservice
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
